- examples/copy.rh
- rash_core/src/error.rs
- rash_core/src/main.rs
- rash_core/src/modules/copy.rs
- rash_core/src/modules/mod.rs
Also, add copy example and implements wrapper for I/O errors.
Add function get_params for modules.
Resolves: #3
> Add module copy

- examples/loop.rh
- rash_core/src/modules/mod.rs
- rash_core/src/task.rs
- rash_core/src/utils/mod.rs
- rash_core/tests/rash_derive.rs
- rash_derive/src/lib.rs
- `get_yaml` is now a public function not just for testing.
- add functions to operate with loop interators and renders at tasks.
- fix rash_derive to support `r#loop` sintax to use protected words as
fields.
Resolves: #8
> Add loop to task attributes

- examples/env.rh
- examples/env_missing.rh
- examples/env_name_missing.rh
- rash_core/src/modules/command.rs
Pass cmd as full argument without spliting to a shell. This allows to
render environment vars at shell and avoid unexpected behaviour about
parsing command lines (old split whitespace).
> [module][command] Fix: execute cmd with sh

- rash_core/src/main.rs
If `-v` is not defined as arg you can setup log level from
`RASH_LOG_LEVEL` environment
variable.
> [cli] Add envar RASH_LOG_LEVEL to define log level

- rash_book/src/contributing.md
- rash_book/src/install.md
- rash_book/src/roadmap.md
- rash_book/src/tasks.md
- rash_book/src/title-page.md
- rash_book/src/vars.md
- rash_core/src/modules/mod.rs
I noticed a few grammar issues and typos in the documentation. It's nothing serious, but I thought it was a good idea to fix those before the documentation grows.
I also fixed some issues pointed out by markdownlint. There's no markdownlint saved in this repo, so those changes might not fit the intended Markdown policy. Feel free to change those if you're not comfortable with them.
> Improve documentation

- rash_core/src/main.rs
- rash_core/src/vars/builtin.rs
`{{ rash.args }}` was returning just the first argument.
Add some basic test to builtins.
> cli: fix multiple args passed

- .cargo-husky/hooks/commit-msg
- .cargo-husky/hooks/pre-commit
- rash_book/src/contributing.md
- rash_core/Cargo.toml
Commit linting is a really powerful technique to ensure commit messages conform to a given format.
However, if users can't have feedback about their commit messages *before* the commits take place, we risk PRs to be rejected by incorrect commit message format. And that situation doesn't have an easy way out.
We'd like our contributors to be happy and feel like they're working in a
friendly environment. That's why I feel that the best approach is to process
every commit message and notify the committer immediately if the commit message
isn't valid. Commits with invalid messages will be rejected, so there aren't
any issues coming up after the fact.
Resolves #88
> Run commitlint on each commit

- rash_core/src/modules/copy.rs
Refactor copy unittest to improve output and fix unitest that was not
working under different umask conditions.
> module: copy fix unittest missing permission setup

- .github/workflows/pages.yml
- Makefile
- mdbook_rash/src/lib.rs
- rash_book/book.toml
- rash_book/src/SUMMARY.md
- rash_book/src/builtins.md
- rash_book/src/contributing.md
- rash_book/src/filters.md
- rash_book/src/getting-started.md
- rash_book/src/index.md
- rash_book/src/lookups.md
- rash_book/src/module_index.md
- rash_book/src/roadmap.md
- rash_book/src/runtime.md
- rash_book/src/tasks.md
- rash_book/src/vars.md
Change all mdbook to produce a markdown output with Jekyll syntax.
This integrates better with rash-sh.github.io and allow better nav
in the website.
> doc: html to jekyll

- Dockerfile
- Dockerfile.debian
- rash_core/src/logger.rs
- rash_core/src/modules/command.rs
- rash_core/src/modules/set_vars.rs
- rash_core/src/modules/template.rs
- rash_core/src/task/mod.rs
- rash_core/src/utils/mod.rs
- rash_core/src/utils/tera.rs
- rash_core/src/vars/env.rs
Fix `cargo clippy` errors and `cargo fmt` errors. Mainly subtitute
`.or_else(|e| Err({{ error }} ))` by `.map_err(|e| {{ error }})`.
> core: update rust to 1.46

- Dockerfile
- Dockerfile.debian
- mdbook_rash/src/lib.rs
Fix `cargo clippy` error `needless_lifetimes`.
> core: update rust to 1.50

- .commitlintrc.json
- .github/workflows/pages.yml
This is necessary to include new versions website.
> ci: Update `_data/projects.json` on gh-pages deploy

- Makefile
- mdbook_rash/Cargo.toml
- rash_core/Cargo.toml
Add version for internal dependencies. This is needed fro crates.io to
allow upload packages.
Also, add auto update these versions in the Makefile as its done for the
others.
> fix(ci): Publish packages to crates.io

- rash_book/src/parser.md
- rash_book/src/syntax.md
- Add indentation.
- Escape special characters with raw mode.
> docs: Fix jekyll config in docopts

- CHANGELOG.md
- README.md
- examples/envar-api-gateway/entrypoint.rh
- examples/php-fpm/entrypoint.rh
- examples/recursivity.rh
- rash_core/src/modules/command.rs
- rash_core/src/task/mod.rs
`transfer_pid_1` will be removed in 1.9.0. From now on is deprecated.
> feat(module): Rename `transfer_pid_1` to `transfer_pid` in command

- .github/workflows/rust.yml
It fails in `rash_core/src/vars/builtin.rs:88` `canonicalize` returning
e.g. `/usr/local/aarch64-linux-musl`.
> fix(ci): remove arm musl builds

- .github/workflows/rust.yml
`cross` has to be cleaned between different targets because reusing builds cause problems with glibc version dependencies
> fix(ci): Enable cache key for different targets

- .github/workflows/aur-publish.yml
- .github/workflows/commitlint.yml
- .github/workflows/docker_images.yml
- .github/workflows/pages.yml
- .github/workflows/rust.yml
- rash_core/src/modules/find.rs
node12 github actions will be deprecated
> fix(ci): Update to node16 github actions

- Cargo.toml
- rash_core/src/docopt/mod.rs
This makes docopt usable when many options are defined.
> fix(core): Improve docopt performance prefiltering possible options

- rash_core/src/bin/rash.rs
- rash_core/src/logger.rs
It omits header and task names with its separator.
> feat(core): Add output option to print log raw mode

- rash_core/src/modules/copy.rs
Rename masked_mode in `change_permissions` and create copy just if needed.
> refactor(module): Improve readalability in Copy

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- mdbook_rash/Cargo.toml
- rash_core/Cargo.toml
- rash_core/src/task/mod.rs
Become was broken because the result from the fork was not correctly deserialized into a `minijinja::Value`.
> fix(task): Add serde to handle result from fork in become tasks

- Cargo.toml
- mdbook_rash/Cargo.toml
- rash_core/Cargo.toml
- rash_derive/Cargo.toml
We should pin minimum required versions in `Cargo.toml`.
> build(deps): Remove pinned versions from `Cargo.toml`

- rash_core/src/docopt/mod.rs
This probably is optimized by the compiler.
> refactor(core): Remove String from function arg

- rash_core/src/docopt/mod.rs
Now, options regex ensure starts with `-`. E.g.:
```
Usage: ./systemctl (daemon-reload|daemon-reexec|help)
```
> fix(core): Fixes docopt command that contains dashes

- examples/setup.rh
- rash_book/src/runtime.md
- rash_core/src/modules/mod.rs
- rash_core/src/modules/setup.rs
- rash_core/src/task/mod.rs
Add a new setup module that enables loading variables from .env, YAML, and JSON files into the Rash templating context. This module follows Ansible's setup module pattern but is adapted for configuration file loading rather than system facts.
Key features:
- Auto-detects file format based on extension and content
- Loads .env variables into the 'env' namespace
- Loads YAML/JSON variables as top-level context variables
- Supports multiple file formats in a single task
- Includes comprehensive unit tests and example usage
The module enhances Rash's configuration management capabilities by providing a standardized way to load external configuration data, making it easier to separate configuration from script logic.
Example usage:
setup:
from:
- .env
- config.yaml - settings.json
Resolves: …
> feat(module): Add setup module for loading variables from config files

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- mdbook_rash/Cargo.toml
- mdbook_rash/src/lib.rs
- rash_core/Cargo.toml
- Apply oneOf variant descriptions to properties when missing
- Flatten whitespace in descriptions to prevent row splits
- Remove debug code and unused imports
> docs: Fix multiline module parameters table format
