rash-sh/rash

examples/template.j2, examples/template.rh, rash_core/Cargo.toml, rash_core/src/facts/builtin.rs, rash_core/src/facts/mod.rs, rash_core/src/lib.rs, rash_core/src/main.rs
* add `facts::builtin` module to get current (dir, user, args).
* add `-- <args>` to parse as input.
Resolves: #6
=> Add builtins

examples/entrypoint.rh, rash_core/Cargo.toml, rash_core/src/lib.rs, rash_core/src/modules/command.rs, rash_core/src/modules/mod.rs, rash_core/src/task.rs, rash_core/src/utils/mod.rs
* Add `get_param_bool` in modules.
* Add exec to execute command when `transfer_ownership` is true.
* Add doc to `get_param`.
* Move `get_yaml` to utils
Resolves: #5
=> [module] Add param `transfer_ownership` to command

rash_core/src/logger.rs, rash_core/src/task.rs
=> [task] add `when` optional field

examples/register.rh, rash_core/src/modules/mod.rs, rash_core/src/task.rs
Add optional register to tasks fields to save results of module into
Facts.
Resolves: #13
=> [task] add `register` optional field

examples/env_missing.rh
=> [doc] Add when dict key is undefined example

README.md, examples/entrypoint.rh, rash_core/src/modules/command.rs
=> [module] Refactor: `transfer_ownership` to `transfer_pid_1`

examples/env.rh, rash_core/src/modules/command.rs, rash_core/src/task/mod.rs
Allow parse command as list of args.
Resolves: #60
=> [module][command] Add argv param

Makefile, README.md, rash_core/Cargo.toml, rash_derive/Cargo.toml
Also change Docker Hub organization to rustagainshell.
=> Change organization to rash-rs

examples/php-fpm/entrypoint.rh, rash_book/src/overview.md
Add a simple example used in a external project
=> Add real world example to doc

README.md, rash_book/src/contributing.md, rash_book/src/install.md, rash_book/src/roadmap.md, rash_book/src/title-page.md, rash_book/src/vars.md, rash_core/src/context.rs, rash_core/src/error.rs, rash_core/src/logger.rs, rash_core/src/main.rs, rash_core/src/modules/command.rs, rash_core/src/modules/copy.rs, rash_core/src/modules/mod.rs, rash_core/src/task/mod.rs, rash_core/src/task/new.rs, rash_core/src/task/valid.rs
I thought it was a good idea to replace passive voice in documentation and comments with active voice. It's not that it's incorrect, but I think it's more readable this way. 
I performed this changes in the documentation and in code comments as well.
I hope this makes reading easier to newcomers!
=> Replace passive voice

rash_core/src/utils/tera.rs
Signed-off-by: Pando85 <pando855@gmail.com>
=> tera: fix trace in `render_string`

.github/workflows/pages.yml, mdbook_rash/src/lib.rs
Add make book to github action pages on releases.
Related with #61
=> ci: add release pages

.github/workflows/rust.yml
=> ci: add publish crates

DCO
=> doc: add dco file

.github/workflows/autotag.yml
This will allow automated releases when changing VERSION file.
=> ci: Add autotag

Cargo.lock, rash_core/Cargo.toml, rash_core/src/modules/copy.rs, rash_core/src/modules/file.rs, rash_core/src/modules/mod.rs, rash_core/src/modules/template.rs
=> module: Add file

.github/workflows/pages.yml, mdbook_rash/src/lib.rs, rash_book/src/builtins.md, rash_book/src/module_index.md, rash_core/src/modules/file.rs
Also:
- Add file module to doc
=> doc: Update mdbook to 0.4.14

README.md, design/concept_map.opml, rash_core/Cargo.toml, rash_core/src/bin/rash.rs, rash_core/src/lib.rs, rash_core/src/modules/assert.rs, rash_core/src/modules/command.rs, rash_core/src/modules/copy.rs, rash_core/src/modules/file.rs, rash_core/src/modules/mod.rs, rash_core/src/modules/set_vars.rs, rash_core/src/modules/template.rs, rash_core/src/task/mod.rs, rash_core/src/task/valid.rs
This allow us to execute rash without making any change.
Resolves: #178
=> feat(core): Add check mode

rash_core/src/modules/assert.rs, rash_core/src/modules/command.rs, rash_core/src/modules/copy.rs, rash_core/src/modules/file.rs, rash_core/src/modules/template.rs
Also, fix parse_params when there are non defined params.
=> feat(module): Add src option to copy module

rash_core/src/bin/rash.rs, rash_core/src/task/mod.rs, rash_core/src/task/valid.rs, rash_core/src/utils/tera.rs
All sentences are concatenated with an `and` for being parsed by Tera.
=> feat(task): Add support for arrays in when and changed_when

design/concept_map.opml, rash_book/src/SUMMARY.md, rash_book/src/docopt.md, rash_book/src/roadmap.md, rash_core/src/bin/rash.rs, rash_core/src/docopt.rs, rash_core/src/error.rs, rash_core/src/lib.rs, rash_core/src/task/mod.rs, rash_core/src/utils/mod.rs
=> feat: add docopt to rash files

rash_book/src/docopt.md, rash_core/src/modules/copy.rs
This allows to preserve original file mode.
Part of #214
=> feat(module): Add preserve mode to copy module

.github/workflows/pages.yml, Cargo.lock, Makefile, design/concept_map.opml, mdbook_rash/Cargo.toml, rash_book/src/tasks.md, rash_core/Cargo.toml, rash_core/src/bin/rash.rs, rash_core/src/error.rs, rash_core/src/lib.rs, rash_core/src/task/mod.rs, rash_core/src/task/valid.rs, rash_core/src/vars/builtin.rs
=> feat(task): Add become

CHANGELOG.md, Makefile, RELEASE.md, mdbook_rash/Cargo.toml, rash_core/Cargo.toml
This fixes packages publishing that was failing
=> fix(ci): Add local versions in dependencies

mdbook_rash/src/lib.rs, rash_core/src/context.rs, rash_core/src/modules/assert.rs, rash_core/src/modules/command.rs, rash_core/src/modules/copy.rs, rash_core/src/modules/debug.rs, rash_core/src/modules/file.rs, rash_core/src/modules/find.rs, rash_core/src/modules/mod.rs, rash_core/src/modules/set_vars.rs, rash_core/src/modules/template.rs, rash_core/src/task/mod.rs, rash_core/src/task/valid.rs
This removes the workaround in the struct Module
=> refactor(module): Implement trait Module

.commitlintrc.json
=> fix(ci): Remove build scope from commitlintrc

rash_core/src/modules/command.rs
=> fix(module): Add trace for command exec

.github/workflows/pages.yml
=> fix(ci): Upgrade mdbook-version to 0.4.21

.github/workflows/pages.yml, Cargo.lock, mdbook_rash/Cargo.toml, mdbook_rash/src/lib.rs
=> build(book): Update mdbook to 0.4.25

CHANGELOG.md, Cargo.lock, Cargo.toml, Dockerfile, mdbook_rash/Cargo.toml, rash_core/Cargo.toml
=> release: v1.8.6

examples/task.rh, rash_book/src/tasks.md, rash_core/src/task/mod.rs, rash_core/src/task/valid.rs
=> feat(task): Add `vars` optional field

Cargo.lock, examples/pacman.rh, examples/task.rh, rash_core/Cargo.toml, rash_core/src/logger.rs, rash_core/src/modules/command.rs, rash_core/src/modules/file.rs, rash_core/src/modules/find.rs, rash_core/src/modules/mod.rs, rash_core/src/modules/pacman.rs, rash_core/src/modules/utils.rs, rash_core/tests/mocks/pacman.rh, rash_core/tests/mod.rs, rash_core/tests/modules/mod.rs, rash_core/tests/modules/pacman.rs, rash_core/tests/rash_derive.rs
=> feat(module): Add pacman

rash_core/Cargo.toml
=> Revert "build(deps): Update Rust crate term_size to 1.0.0-beta1"

examples/dotfiles/dots
Reorder tasks and fix when package_filters is defined
=> docs: Update dots example

CHANGELOG.md, Cargo.lock, Cargo.toml, mdbook_rash/Cargo.toml, rash_core/Cargo.toml, rash_core/src/jinja/mod.rs, rash_core/src/modules/mod.rs, rash_core/src/modules/pacman.rs, rash_core/src/task/mod.rs, rash_core/tests/modules/pacman.rs
Allows pacman module to get a list from a variable.
=> feat(module): Make `render_params` force string optional

.github/workflows/rust.yml, Makefile
=>  fix(ci): Remove deprecated action-rs

.github/workflows/rust.yml
20.04 -> 22.04
22.04 -> 24.04
Resolves actions/runner-images#11101.
=> build(ci): Update ubuntu runners

CHANGELOG.md, Cargo.lock, Cargo.toml, mdbook_rash/Cargo.toml, rash_core/Cargo.toml
=> build: Update `ipc-channel` to `82f6c49`

examples/blocks.rh, examples/rescue_always.rh, rash_core/src/context.rs, rash_core/src/modules/block.rs, rash_core/src/modules/mod.rs, rash_core/src/task/mod.rs, rash_core/src/task/valid.rs
=> feat(task): Add block attribute

examples/lineinfile.rh, rash_core/src/modules/lineinfile.rs, rash_core/src/modules/mod.rs
=> feat(module): Add lineinfile

examples/pipe.rh, rash_core/src/jinja/lookup/mod.rs, rash_core/src/jinja/lookup/pipe.rs
=> feat(lookup): Add pipe

Cargo.lock, rash_core/Cargo.toml, rash_core/src/jinja/lookup/mod.rs, rash_core/src/jinja/lookup/vault.rs
=> feat(lookup): Add vault

examples/lookup.rh, rash_core/src/jinja/lookup/file.rs, rash_core/src/jinja/lookup/mod.rs
=> feat(lookup): Add file

CHANGELOG.md, Cargo.lock, Cargo.toml, mdbook_rash/Cargo.toml, rash_core/Cargo.toml, rash_core/src/modules/pacman.rs, rash_core/tests/cli/modules/pacman.rs
=> fix(module): Improve cmd error and remove Pacman executable detection
